version: '3'
services:
  qlik2datarobot:
    image: analyticsearth/qlik2datarobot
    deploy:
      replicas: 1
    ports:
      - "50052:50052/tcp"
      - "19345:19345/tcp"       
    volumes:
      - /labdata/DataRobot:/dr
    environment:
      - qlik2datarobot_certificateFolder=/dr/sse_DataRobot_server_certs
